menu:
    主页: /
    过往: /archives/
    联系我: /about-me

favicon: /favicon.png
logo: /logo.svg

# Comment
# e.g disqus: seansun
disqus: chen-leon
duoshuo:

# Analytics
# google-analytics:
ga: UA-106539432-1

# Copyright Infomation
startyear: 2017
