menu:
    主页: /
    过往: /archives/
    联系我: /about-me

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
gitalk:
    client_id: "11849e59f7c76ceea9ba"
    client_secret: "372fe5487c8a39b4dce6be464fe0d4d6e94917d6"
    owner: leonfancy
    admin: ['leonfancy']
    repo: leonfancy.github.io

# Analytics
# google-analytics:
ga: UA-106539432-1

# Copyright Infomation
startyear: 2017
